### PR TITLE
Add breakage example 'enum/breaks/add_to_SizeEnum'

### PR DESCRIPTION
**Pull request by hainest**
This adds a single enumerator to an enum. At least libabigail/abicomp should report this as a breakage.

Signed-off-by: Tim Haines <thaines.astro@gmail.com>

### CODE REVIEW

**Comment by vsoch** [comment]
yay! Ok with you if we make the sub folder names all lowercase? I can change it later when I work on the new automation! Going to go outside for a bit to scream into the sky.  😆

**Comment by hainest** [comment]
Done! I think that was the example you had, but I can't read.

**Comment by vsoch** [comment]
My bad! 😆 

I’ll try to hammer this out tonight - I think we could easily get this one test run done, I haven’t been sleeping super well so Im reliable for that, lol.

**Comment by vsoch** [comment]
@hainest I'm not super great with makefiles, but before I update them all can you take a look at? https://github.com/buildsi/smeagle-examples/pull/32/commits/427cfcbcef72e7771fa76e73f2df74a82b485ef9

Basically I want to add in a variable for the compiler and flags that we can pass from the workflow.

**Comment by hainest** [comment]
Make has a few features that can make this simpler at the cost of one extra Makefile.

- `CC` is for the C compiler, `CXX` is for the C++ compiler. Similarly for `CFLAGS`.
- Default variable values are usually specified with the `?=` operator to prevent accidentally overwriting a user-provided value
- You can create targets from any string, so each example can be its own target. This let's you build just one example (e.g., `make enum`).

The big change here is to let the enum/Makefile build the enum/breaks. This is where we need an extra Makefile to track the subdirectories for enum/breaks/*.

I'll push a commit in a sec.

**Review by vsoch — APPROVED** [review]

**Pull request merged**
